apiVersion: v1
kind: Service
metadata:
  name: ppp-grpc
spec:
  clusterIP: None
  selector:
    k8s-app: ppp-grpc
  ports:
    - port: 10000
      name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppp-grpc
  labels:
    k8s-app: ppp-grpc
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: ppp-grpc
  template:
    metadata:
      labels:
        k8s-app: ppp-grpc
    spec:
      containers:
        - name: ppp-grpc
          image: __IMAGE__@__DIGEST__
          ports:
            - containerPort: 10000
              name: grpc
